name: suricata

include:
  - ../testserver/docker-compose.yml

services:
  suricata:
    container_name: "suricata"
    build:
      context: "containers/suricata"
      args:
        - CONNECTOR_CONFIG_FILE
    volumes:
      - type: "bind"
        source: "${IDMEFV2_CONNECTORS_GIT}"
        target: "/idmefv2-connectors"
    network_mode: "host"
    command: /entrypoint.sh -i ${INTERFACE}
